version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: preprocess-clean-node-modules
          command: rm -rf node_modules
      - run:
          name: preprocess-npm
          command: npm install
      - run:
          name: test (npm)
          command: npm run test
      - run:
          name: preprocess-yarn
          command: yarn
      - run:
          name: test (yarn)
          command: yarn run test